<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            label {
                vertical-align: top;
            }

            textarea {
                width: 50%;
            }
        </style>
    </head>
    <body>
        <h1>Tozny SMS Verification</h1>
        <div>Use the Tozny out-of-band verification API to confirm ownership of a phone number</div>

        <p>Validated!</p>

        <div>
            <p>The following is the <i>raw</i> data returned from the Tozny API:</p>
            <label for="signed_data">Signed Data:</label>
            <textarea cols="30" rows="5" name="signed_data"><?php echo $signed_data; ?></textarea>
            <label for="signed_data">Signature:</label>
            <textarea cols="30" rows="1" name="signed_data"><?php echo $signature; ?></textarea>
        </div>

        <div>
            <p>The following is the <i>decoded</i> data that Tozny associated with the OTP session:</p>

            <div style="text-align: left; margin-left:25%; width: 50%; color: black; font-size: 14px;">
                <pre><?php echo json_encode( $data, JSON_PRETTY_PRINT ); ?></pre>
            </div>
        </div>
    </body>
</html>
