<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 40px;
                font-weight: 200;
                margin-bottom: 20px;
            }
            table {
                margin: auto;
            }
            table td {
                text-align: left;
            }
        </style>
    </head>
    <body>
        <h1>Tozny SMS Verification Demo</h1>

        <section id="errors">
            <?php if ( isset( $error ) ) : ?>
                <p><?php echo $error; ?></p>
            <?php endif; ?>
        </section>

        <section id="main">
            <p>Please enter the one-time password you recieved via SMS to finish registration.</p>
            <form method="post" action="/verify">
                <table>
                    <tr>
                        <td>
                            <label for="otp">One-time Password</label>
                        </td>
                        <td>
                            <input type="text" name="otp" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center;">
                            <input type="hidden" name="session" value="<?php echo $session_id; ?>" />
                            <input type="submit" value="Verify" />
                        </td>
                    </tr>
                </table>
                <p><a href="/">Login</a></p>
            </form>
        </section>
    </body>
</html>
